// Shared tag vocabulary used by quiz and chat onboarding.
// Keep IDs stable: they map into backend scoring/tag registry.

export const ALL_TAGS = [
  { id:'cafes_brunch', title:'Cafes & brunch', sub:'Coffee spots, local vibe, weekend brunch' },
  { id:'restaurants', title:'Restaurants', sub:'Dining scene and variety' },
  { id:'nightlife', title:'Nightlife', sub:'Bars, late evenings, lively streets' },
  { id:'culture_museums', title:'Culture & museums', sub:'Museums, theaters, cultural venues' },
  { id:'art_design', title:'Art & design vibe', sub:'Architecture, galleries, creative feel' },
  { id:'shopping', title:'Shopping', sub:'Shops, boutiques, retail streets' },
  { id:'local_market_vibe', title:'Markets & local feel', sub:'Weekend markets, neighborhood vibe' },
  { id:'touristy', title:'Touristy / central sights', sub:'Higher visitor density, landmarks' },
  { id:'families', title:'Family-friendly', sub:'Services for kids, calmer micro-areas' },
  { id:'expats_international', title:'International / expat-friendly', sub:'International community, languages' },
  { id:'students', title:'Student vibe', sub:'Universities, student life' },
  { id:'young_professionals', title:'Young professionals', sub:'After-work vibe, convenience' },
  { id:'older_quiet', title:'Older / quiet vibe', sub:'Calmer pace, residential feel' },
  { id:'green_parks', title:'Parks & green areas', sub:'Parks, nature, playgrounds' },
  { id:'residential_quiet', title:'Residential & quiet', sub:'Lower noise, calmer streets' },
  { id:'urban_dense', title:'Urban & dense', sub:'City feel, dense blocks' },
  { id:'houses_more', title:'More houses', sub:'Higher share of houses, gardens' },
  { id:'apartments_more', title:'More apartments', sub:'Higher share of apartments' },
  { id:'premium_feel', title:'Premium feel', sub:'Higher-end housing & services' },
  { id:'value_for_money', title:'Value for money', sub:'More space/price balance (micro-area dependent)' },
  { id:'mixed_vibes', title:'Mixed vibes', sub:'Micro-areas vary a lot' },
  { id:'central_access', title:'Central access', sub:'Easy access to city centre' },
  { id:'eu_quarter_access', title:'EU quarter access', sub:'Convenient to EU Quarter area' },
  { id:'train_hubs_access', title:'Train hubs access', sub:'Convenient to major stations' },
  { id:'airport_access', title:'Airport access', sub:'Convenient to airport' },
  { id:'metro_strong', title:'Strong metro', sub:'Metro coverage & access' },
  { id:'tram_strong', title:'Strong tram', sub:'Tram coverage & access' },
  { id:'bike_friendly', title:'Bike friendly', sub:'Bike infrastructure & comfort' },
  { id:'car_friendly', title:'Car friendly', sub:'Ease of driving/parking (varies)' },
  { id:'night_caution', title:'Night caution', sub:'More caution at night (micro-area dependent)' },
  { id:'busy_traffic_noise', title:'Traffic/noise', sub:'Busier roads, noise levels (varies)' },
  { id:'schools_strong', title:'Schools access', sub:'Proximity and density of schools' },
  { id:'childcare_strong', title:'Childcare access', sub:'Nurseries, childcare access' },
]
